USE [master]
GO
/****** Object:  Database [GroupStudyV2]    Script Date: 6/10/2025 8:52:28 PM ******/
CREATE DATABASE [GroupStudyV2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GroupStudyV2', FILENAME = N'/var/opt/mssql/data/GroupStudyV2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GroupStudyV2_log', FILENAME = N'/var/opt/mssql/data/GroupStudyV2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GroupStudyV2] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GroupStudyV2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GroupStudyV2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GroupStudyV2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GroupStudyV2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GroupStudyV2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GroupStudyV2] SET ARITHABORT OFF 
GO
ALTER DATABASE [GroupStudyV2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GroupStudyV2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GroupStudyV2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GroupStudyV2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GroupStudyV2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GroupStudyV2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GroupStudyV2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GroupStudyV2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GroupStudyV2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GroupStudyV2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GroupStudyV2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GroupStudyV2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GroupStudyV2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GroupStudyV2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GroupStudyV2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GroupStudyV2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GroupStudyV2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GroupStudyV2] SET RECOVERY FULL 
GO
ALTER DATABASE [GroupStudyV2] SET  MULTI_USER 
GO
ALTER DATABASE [GroupStudyV2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GroupStudyV2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GroupStudyV2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GroupStudyV2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GroupStudyV2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GroupStudyV2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GroupStudyV2', N'ON'
GO
ALTER DATABASE [GroupStudyV2] SET QUERY_STORE = ON
GO
ALTER DATABASE [GroupStudyV2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GroupStudyV2]
GO
/****** Object:  Table [dbo].[Assignments]    Script Date: 6/10/2025 8:52:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Assignments](
	[AssignmentId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[DueDate] [datetime2](7) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
	[CourseId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AssignmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Courses]    Script Date: 6/10/2025 8:52:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Courses](
	[CourseId] [int] IDENTITY(1,1) NOT NULL,
	[CourseCode] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CourseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CourseCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudentAssignments]    Script Date: 6/10/2025 8:52:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudentAssignments](
	[StudentAssignmentId] [int] IDENTITY(1,1) NOT NULL,
	[StudentId] [int] NOT NULL,
	[AssignmentId] [int] NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StudentAssignmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Students]    Script Date: 6/10/2025 8:52:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students](
	[StudentId] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[ClassStanding] [nvarchar](50) NULL,
	[Gender] [nvarchar](20) NULL,
	[Age] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[StudentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudyGroupMembers]    Script Date: 6/10/2025 8:52:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudyGroupMembers](
	[StudyGroupMemberId] [int] IDENTITY(1,1) NOT NULL,
	[StudyGroupId] [int] NOT NULL,
	[StudentId] [int] NOT NULL,
	[JoinedOn] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StudyGroupMemberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudyGroups]    Script Date: 6/10/2025 8:52:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudyGroups](
	[StudyGroupId] [int] IDENTITY(1,1) NOT NULL,
	[AssignmentId] [int] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[GroupName] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[StudyGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Assignments] ADD  CONSTRAINT [DF_Assignments_CourseId]  DEFAULT ((1)) FOR [CourseId]
GO
ALTER TABLE [dbo].[StudentAssignments] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedOn]
GO
ALTER TABLE [dbo].[StudyGroupMembers] ADD  DEFAULT (sysutcdatetime()) FOR [JoinedOn]
GO
ALTER TABLE [dbo].[StudyGroups] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedOn]
GO
ALTER TABLE [dbo].[Assignments]  WITH CHECK ADD  CONSTRAINT [FK_Assignments_Courses] FOREIGN KEY([CourseId])
REFERENCES [dbo].[Courses] ([CourseId])
GO
ALTER TABLE [dbo].[Assignments] CHECK CONSTRAINT [FK_Assignments_Courses]
GO
ALTER TABLE [dbo].[StudentAssignments]  WITH CHECK ADD  CONSTRAINT [FK_StudentAssignments_Assignments] FOREIGN KEY([AssignmentId])
REFERENCES [dbo].[Assignments] ([AssignmentId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[StudentAssignments] CHECK CONSTRAINT [FK_StudentAssignments_Assignments]
GO
ALTER TABLE [dbo].[StudentAssignments]  WITH CHECK ADD  CONSTRAINT [FK_StudentAssignments_Students] FOREIGN KEY([StudentId])
REFERENCES [dbo].[Students] ([StudentId])
GO
ALTER TABLE [dbo].[StudentAssignments] CHECK CONSTRAINT [FK_StudentAssignments_Students]
GO
ALTER TABLE [dbo].[StudyGroupMembers]  WITH CHECK ADD  CONSTRAINT [FK_StudyGroupMembers_Groups] FOREIGN KEY([StudyGroupId])
REFERENCES [dbo].[StudyGroups] ([StudyGroupId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[StudyGroupMembers] CHECK CONSTRAINT [FK_StudyGroupMembers_Groups]
GO
ALTER TABLE [dbo].[StudyGroupMembers]  WITH CHECK ADD  CONSTRAINT [FK_StudyGroupMembers_Students] FOREIGN KEY([StudentId])
REFERENCES [dbo].[Students] ([StudentId])
GO
ALTER TABLE [dbo].[StudyGroupMembers] CHECK CONSTRAINT [FK_StudyGroupMembers_Students]
GO
ALTER TABLE [dbo].[StudyGroups]  WITH CHECK ADD  CONSTRAINT [FK_StudyGroups_Assignments] FOREIGN KEY([AssignmentId])
REFERENCES [dbo].[Assignments] ([AssignmentId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[StudyGroups] CHECK CONSTRAINT [FK_StudyGroups_Assignments]
GO
ALTER TABLE [dbo].[StudyGroups]  WITH CHECK ADD  CONSTRAINT [FK_StudyGroups_Students] FOREIGN KEY([CreatedBy])
REFERENCES [dbo].[Students] ([StudentId])
GO
ALTER TABLE [dbo].[StudyGroups] CHECK CONSTRAINT [FK_StudyGroups_Students]
GO
USE [master]
GO
ALTER DATABASE [GroupStudyV2] SET  READ_WRITE 
GO
